### ISSUE TITLE
Sorry, I cannot find any reasonable answer for your query.

### ISSUE THREAD

**Issue by josephhyatt** [santinic/how2#93] opened 2019-06-19 03:47 UTC
No matter what question I ask (even your example question) I keep getting "Sorry, I cannot find any reasonable answer for your query." 

Example question:
how2 read file while is changing

**Comment by pgcudahy** [comment] 2019-06-20 08:14
Same here

**Comment by amishPro** [comment] 2019-06-20 17:38
Same here. No matter what questions it returns "Sorry, I cannot find any reasonable answer for your query." I have installed it with "sudo npm install -g how-2".

**Comment by Tom-Hayes** [comment] 2019-06-21 14:07
Same here!

**Comment by aranmohyeddin** [comment] 2019-06-29 05:28
same here even with the question `how2 unzip bz2` which is illustrated in the readme:))
I installed without sudo.

**Comment by martinstepanek** [comment] 2019-07-08 09:48
Same here and because last version is 3 years old, I guess one of the APIs changed.

**Comment by LeonAlvarez** [comment] 2019-07-29 17:03
still broken

**Comment by PaoloCifariello** [comment] 2019-07-31 11:27
Hi guys and thank you for letting me know about this.

I immediately thought that this was caused by https://github.com/jprichardson/node-google. 
I discovered that the library successfully retrieves an HTML containing the results, but unfortunately something changed in the response format, hence results are no more correctly parsed (this should be the broken line https://github.com/jprichardson/node-google/blob/master/lib/google.js#L68)

To fix this I should probably play a bit with `cheerio` and the produced HTML to see if I can extract results,  changing the old `div.g`, which is apparently no more a valid selector.

My idea would be to also include that single-file-library (which is apparently not supported anymore) in this project and, eventually, switch from `requests` to `axios` to have `Promise` support in addition to this fix.

Feel free to help on this if you want/can.

**Comment by tomhayes** [comment] 2019-07-31 11:35
I really wish I had the know-how to help you out with this, sorry!

<http://tomhay.es>

Tom Hayes Web/Graphic Designer
hello@tomhay.es | http://tomhay.es
07889874933

[image: Twitter]  <https://twitter.com/tomhayesdesign> [image: LinkedIn]
<https://www.linkedin.com/in/tdhayes> [image: Skype]  [image: Facebook]
<https://www.facebook.com/tomhayesdesign>

**Comment by VladimirMikulic** [comment] 2019-08-15 14:56
> I immediately thought that this was caused by https://github.com/jprichardson/node-google.
> I discovered that the library successfully retrieves an HTML containing the results, but unfortunately something changed in the response format, hence results are no more correctly parsed (this should be the broken line https://github.com/jprichardson/node-google/blob/master/lib/google.js#L68)
> 
> To fix this I should probably play a bit with `cheerio` and the produced HTML to see if I can extract results, changing the old `div.g`, which is apparently no more a valid selector.

I've noticed that also, but since I discovered a new library that is maintained, I decided to modify it a bit to suit our needs and removed the old one.

> My idea would be to also include that single-file-library (which is apparently not supported anymore) in this project and, eventually, switch from `requests` to `axios` to have `Promise` support in addition to this fix.

I can do it in the next PR :smile:

**Comment by VladimirMikulic** [comment] 2019-08-15 15:43
@josephhyatt @pgcudahy @tomhayes @aranmohyeddin while we wait for the PR to be processed, you can download and install how2 from [my Github repo](https://github.com/VladimirMikulic/how2) and test it.

```bash
git clone https://github.com/VladimirMikulic/how2
sudo npm i -g ./how2
```

Enjoy  :rocket: :rocket: :rocket:

**Comment by petRUShka** [comment] 2019-08-29 07:59
@VladimirMikulic, could you please provide release section with downloadable `tgz` npm package?

Like this one from npm repository: https://registry.npmjs.org/how2/-/how2-1.7.1.tgz

It is needed to create Arch linux PKGBUILD.

**Comment by VladimirMikulic** [comment] 2019-08-29 08:28
@petRUShka as you wished, I added a release section. Good luck with Arch BTW :)

**Comment by petRUShka** [comment] 2019-08-29 09:41
@VladimirMikulic, thanks!

**Comment by aranmohyeddin** [comment] 2019-08-29 10:49
@petRUShka  Thank you for maintaining the PKGBUILD ;)

**Comment by petRUShka** [comment] 2019-08-29 20:14
@aranmohyeddin, @VladimirMikulic, `how2` package uses @VladimirMikulic fork right now.

**Comment by VladimirMikulic** [comment] 2019-08-29 21:18
@petRUShka I'll keep it updated, feel free to suggest new features & report bugs.
I fixed the "b" keyboard shortcut for opening a link in the browser.
I could also publish it to the NPM registry, it would be easier to install(and keep it up to date).

**Comment by iamaziz** [comment] 2019-09-21 02:22
@VladimirMikulic I wanna give to likes if GitHub allows! Big Thanks 👍🏻

**Comment by PaoloCifariello** [comment] 2019-09-21 18:01
@VladimirMikulic thanks a lot for suggesting `google-it` as new package to query Google and obtain results.
I saw you forked `google-it` to make some small adjustments, but I preferred to keep the ["official version"](https://github.com/PatNeedham/google-it/) as it seems to be constantly updated.

I just updated `how-2` to `1.8.0` on NPM and merged in masters the code using the new package. 
Thanks to everybody and sorry for this loooong issue.

**Closed by PaoloCifariello** 2019-09-21 18:01 UTC

**Comment by VladimirMikulic** [comment] 2019-09-21 18:10
@PaoloCifariello glad you came back. Next time when you want to go on vacation feel free to message me :)

**Comment by svscorp** [comment] 2019-09-26 12:02
Hi @PaoloCifriello,

Thank you for returning on that. Not sure it is related to the latest fix, but strangely after update query like "how2 fly to the moon" return error. Maybe it should resolve it that way for these non-it related queries.

**Comment by rowan-schaefer** [comment] 2023-02-07 04:09
I am now getting this error, after the AI bit has been added. Never had it back when it was only stackoverflow. 

"Sorry, I cannot find any reasonable answer for your query." Has anyone else encountered this after the update?
